<?
include('header.php');
?>
  <script type="text/javascript">
    
    function addRecentActivities(img, id, titel){
      $('#recentActivities').append('<li class="customLi"><img src="'+img+'" style="height: 30px; margin-right: 10px; "/><a href="'+id+'">'+titel+'</a></li>');
    }

    function addFriendActivities(actionImg, friendImg, id, titel){
      $('#friendActivities').append('<li class="customLi"><img src="'+actionImg+'" style="height: 30px; margin-right: 10px; "/><a href="'+id+'">'+titel+'</a><img src="'+friendImg+'" style="height: 30px; margin-right: 10px; float:right; "/></li>');
    }

  </script>

  
  
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">

  <div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne" show >
       Main Information
      </a>
    </div>
      <div class="offset2">
	  <div class="accordion-inner" >
         <a href="http://giv-cario.uni-muenster.de/working-folder/support"> What is EnviroCar? </a>
		 </a>
      </div></div>
	   <div class="offset2">
	  <div class="accordion-inner">
        		<a href="http://giv-cario.uni-muenster.de/working-folder/howenvirocworks.php"> How EnviroCar works? </a> 

      </div></div>
 
  </div>
  
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Mobile Application
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
       <div class="offset2">
	  <div class="accordion-inner">
        <a href="http://giv-cario.uni-muenster.de/working-folder/support_reg.php"> Registration</a>
      </div></div>
	   <div class="offset2">
	  <div class="accordion-inner">
        <a href="http://giv-cario.uni-muenster.de/working-folder/support_down.php"> Downloading</a>
      </div></div>
	   <div class="offset2">
	  <div class="accordion-inner">
        <a href="http://giv-cario.uni-muenster.de/working-folder/support_sync.php"> synchronization</a>
      </div></div>
    </div>
	
	
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
       WebSite
      </a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
	   <div class="offset2">
        <a href="http://giv-cario.uni-muenster.de/working-folder/support_compare.php"> Compare Your Data</a>
      </div></div>
	   <div class="offset2">
	  <div class="accordion-inner">
       <a href="http://giv-cario.uni-muenster.de/working-folder/share.php"> Share Your Data </a>
</div>
      </div>
    </div>
 
  </div>
  
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
         <a href="http://giv-cario.uni-muenster.de/working-folder/faq.php">  FAQ </a>
      </a>
    </div>
  </div>
</div>
	</div>
	
	
	<!--Data-->
	 
 <div class="span10">
          <div class="hero-unit">
            <h2>How EnviroCar Works?</h2>
			 <img class="offset2" src="./assets/img/paper_architecture.png"  height="400" width="600" >
			    <p>  
			enviroCar uses an OBD2 adapter that you can easily plug into your car to access data generated by the various sensors of your car. The enviroCar App installed on your smartphone is able to connect automatically to that OBD2 adapter to read out parameters from your car, such as current fuel consumption or revolutions per minute. This way, enviroCar can accurately measure your driving costs, can compute emitted CO2 or even estimate the noise created by your car.
</br>
<img class="offset2" src="./assets/img/obd_adapter.png" height="300" width="500" >
</br>
By using OBD2 adapter, enviroCar is able to receive your cars data by pairing your smartphone via Bluetooth with the adapter. The smartphone app analyzes and parses the data to give you in the app and on the enviroCar these information, which you want to see.

				
				</p>
              </div>
	
	</div>

	 </div>



  
  
  
  
  
<?
include('footer.php');
?>
