<?
include('header_new.php');
?>


<script type="text/javascript">
$('#myTab a').click(function(e) {
    e.preventDefault();
    $(this).tab('show');
})



$('#myTab a:last').tab('show');


</script>
<div class="container">
<div class="row">
<div class="tabbable">

    <ul id="myTab" class="nav nav-tabs" >
      <li><a href="#main" data-toggle="tab" ><strong>Main Information</strong></a></li>
      <li><a href="#mobile" data-toggle="tab"> <strong> Mobile Application</strong></a></li>
      <li><a href="#website" data-toggle="tab"> <strong> WebSite</strong></a></li>
      <li><a href="#faqs" data-toggle="tab"><strong> FAQs</strong></a></li>
    </ul>
  </div>
    <div class="tab-content">
	
      <div class="tab-pane fade in active" id="main">
		 
	<div class="row-fluid">

				<ul>
					<li><a href="#what">What is EnviroCar?</a></li>		
					<li><a href="#how">How EnviroCar works?</a></li>	
				</ul>
				</div>
 <div class="container rightband">
 <div class="row-fluid">
		<div class="span9 offset1">
	  		<div class="customLi"><h1 name="what">What is EnviroCar?</h1></br></br>
			
			<img class="offset2" src="./assets/img/architecture_new3.svg" height="400" width="600" >
			   </br></br> <p style="text-align: justify;">  
				A community based system for gathering you car’s data via with your smartphone bluetooth-paired OBD2 adapter to 
				make your city smarter.	</br>enviroCar allows you to drive more efficiently by giving you for example full 
				insight in consumption and costs. It allows you to compare your driving statistics with friends and to enjoy 
				competing to become the most efficient driver. Furthermore, enviroCar enables you to contribute data collected 
				by your car to the open enviroCar community. </br></br>From those data,	enviroCar generates information about 
				traffic in your city and its emissions on our streets. The information will support e.g. urban planners to improve
				traffic light phases or to clarify the impact of traffic calming measures. </br>enviroCar is the first platform to 
				collect information about the actual emissions right when they happen because it is connected directly to the sensors in the car.
				Join the community and help to make our world a little smarter, traffic less stressful, and economic driving more fun!
				</p>
				
				<p class="pull-right"><a href="#">Back to top</a></p>

         </div>    
           </div>    
         </div>    
         </div>
		 
<div class="container leftband">
 <div class="row-fluid">
		<div class="span9 offset1">
	  		<div class="customLi"><h1 id="how">How EnviroCar works?</h1>
				 <p style="text-align: justify;"> enviroCar uses an OBD2 adapter that you can easily plug into your car to access data generated by the 
				 various sensors of your car. The enviroCar App installed on your smartphone is able to connect automatically
				 to that OBD2 adapter to read out parameters from your car, such as current fuel consumption or revolutions 
				 per minute. This way, enviroCar can accurately measure your driving costs, can compute emitted CO2 or even 
				 estimate the noise created by your car.
				</br> <img class="offset2" src="./assets/img/obd_adapter.png" height="200" width="400" >
				</br>By using OBD2 adapter, enviroCar is able to receive your cars data by pairing your smartphone via Bluetooth with the adapter. The smartphone app analyzes and parses the data to give you in the app and on the enviroCar these information, which you want to see.
				</p>
				<p class="pull-right"><a href="#">Back to top</a></p>
             </div>    
           </div>    
         </div>    
         </div>
		 
</div>		 
   <!--end of div id="main"-->
     
	 <div class="tab-pane fade in " id="mobile">
		<ul>
			<li><a href="#reg">Regestration</a></li>		
			<li><a href="#down">Downloading</a></li>	
			<li><a href="#sync">Synchronization</a></li>
		</ul>
		<div class="container rightband">
			<div class="row-fluid">
				<div class="span10 offset1">
				<div class="customLi"><a name="reg">Regestration</a>
					<p>  
							registration Steps ... </br> .. </br> ... </br> .. </br>... </br> .. </br>
					</p>
					
					<p class="pull-right"><a href="#">Back to top</a></p>
			 </div>    
			   </div>    
            </div>    
         </div>
		 <div class="container leftband">
			<div class="row-fluid">
				<div class="span10 offset1">
				<div class="customLi"><a name="down">Downloading</a>
					<p>  
							Downloading Steps ... </br> .. </br> ... </br> .. </br>... </br> .. </br>
					</p>
					
					<p class="pull-right"><a href="#">Back to top</a></p>
			 </div>    
			   </div>    
            </div>    
         </div>
		<div class="container rightband">
			<div class="row-fluid">
				<div class="span10 offset1">
				<div class="customLi"><a name="sync">synchronization</a>
					<p>  
							synchronization Steps ... </br> .. </br> ... </br> .. </br>... </br> .. </br>
					</p>
					
					<p class="pull-right"><a href="#">Back to top</a></p>
			 </div>    
			   </div>    
            </div>    
         </div>
	 
	 </div>
     <!--end of div id="mobile"-->
	  <div class="tab-pane fade in " id="website">
	  
	  </div> 
      <!--end of div id="website"-->
	  <div class="tab-pane fade in " id="faqs">
	  
	  </div>
<!--end of div id="faqs"-->   
   </div>
   
	    </div>
		 </div>


<?
include('footer.php');
?>
