<?php 
// index.php
$index_invalid_login_name="Invalid Login Name"; 
$index_empty_password="Password cannot be empty"; 
$index_access_denied="Access denied!";
$index_Please_sign_in="Please sign in";
$index_password="Password";
$index_user_details="User details";
$index_register="Register";
$index_get_App="Get our App soon!";
$index_get_it_on_google="Get it on Google Play!";
$index_be_a_citizen_scientist="Be a Citizen Scientist";
$index_help_the_world="Help the world become a better place by sharing your data with scientists from all over the world! Or use existing data for your own research!";
$index_support_indiegogo="Support us on Indiegogo";
$index_this_is_community="This is a community, it's an app and it's a website.<br> enviroCar is our contribution to a smarter world.<br> We will generate knowledge about car traffic and its emissions on our streets and we will raise awareness of environmental consequences of our driving behaviour.";
$index_how_it_works="How does it work?";
$index_three_steps_to="Three steps to become a citizen scientist";
$index_register="Register";
$index_sign_in="Sign in";
$index_user_name="User name";
$index_make_smarter="Make our cities smarter!";
$index_empty_password="sorry, but you can't have an empty password.";
$index_name_missing="everybody should have a name, even you.";
$index_credentials_invalid="nice try, but empty credentials are invalid.";
$index_having_account="Are you sure of having an account?";
$index_create_new_one="You can create a new one. It's free";
$index_wrong_name="Wait, that's not my name!";
$index_continue_dashboard="Continue to your profile";
$index_welcome="Welcome";

// registration.php
$reg_registration="Registration";
$reg_username="User name";
$reg_email="Email Address";
$reg_password="Password";
$reg_repeat_password="Repeat Password";
$reg_btn_register="Register";
$reg_btn_reset="Reset";
$invalid_input ="Invalid input. Please check the hints and try again.";


// dashboard.php
$dashboard_recent_avtivities="Recent Activities";
$dashboard_view_details="View details";
$dashboard_overview="Overview";
$dashboard_friend_activities="Friend Activities";
$dashboard_group_activities="Group Activities";
$dashboard_activities_of="Activities of ";

//function registration
$freg_invalidemail="Invalid Email";
$freg_empty_nickname="Nickname cannot be empty";
$freg_empty_password="Password cannot be empty";
$freg_notidentic_password='Passwords are not identic';

// Support
$main_information="Main information";
$mobile_app="Mobile application";
$website="Website";
$what_enviro="What is enviroCar?";
$how_enviro="How does enviroCar work?";
$enviro_description="A community based system for gathering your car’s data with your smartphone bluetooth-paired OBD2 adapter to 
								make your city smarter.	<br/>enviroCar allows you to drive more efficiently by giving you for example full 
								insight in consumption and costs. It allows you to compare your driving statistics with friends and to enjoy 
								competing to become the most efficient driver. Furthermore, enviroCar enables you to contribute data collected 
								by your car to the open enviroCar community. <br/><br/>From those data,	enviroCar generates information about 
								traffic in your city and its emissions on our streets. The information will support e.g. urban planners to improve
								traffic light phases or to clarify the impact of traffic calming measures. <br/>enviroCar is the first platform to 
								collect information about the actual emissions right when they happen because it is connected directly to the sensors in the car.
								Join the community and help to make our world a little bit smarter, traffic less stressful, and economic driving more fun!";
$back_top="Back to top";
$enviro_description_detail="enviroCar uses an OBD2 adapter that you can easily plug into your car to access data generated by the 
								various sensors of your car. The enviroCar App installed on your smartphone is able to connect automatically
								to that OBD2 adapter to read out parameters from your car, such as current fuel consumption or revolutions 
								per minute. This way, enviroCar can accurately measure your driving costs, can compute emitted CO2 or even 
								estimate the noise created by your car.";
$enviro_description_detail2="By using OBD2 adapter, enviroCar is able to receive your cars data by pairing your smartphone via Bluetooth with the adapter. The smartphone app analyzes and parses the data to give you in the app and on the enviroCar these information, which you want to see.";

//Support_mobile_application
$how_register="How to register from your mobile phone?";
$how_download="How to download the enviroCar application?";
$how_synchronize="How to synchronize your data?";
$registration="Registration";
$registration_steps="Of course you can register a new user account via the enviroCar app.<br><ol><li>After installing and starting the app on your smartphone, open the menu and click on “Sign in/Register”.</li><li>Click on the upper right button to create a new user account.</li><li>Fill in your user credentials. Click on “Register” to create a new user account.<br><img src='assets/img/support_app/img1.png' alt='Registration step 1' width='20%'><img src='assets/img/support_app/img2.png' alt='Registration step 2' width='20%'><img src='assets/img/support_app/img3.png' alt='Registration step 3' width='20%'></li></ol>";
$downloading="Downloading";
$download_steps="The enviroCar App is available for Android 2.3 to the latest version 4.2.2. To install the app on your smartphone, you can use the <a href='https://play.google.com/store'>Google Play Webstore</a> or the Play Store, which is installed on your Android smartphone.<br>You can find us with the name “enviroCar”. Download and install this app on your smartphone and enjoy all the features enviroCar system offers.";
$synchronization="Synchronization";
$synchronization_steps="To upload your generated data, you have two options.<br><ol><li>Upload your data automatically. Either while using a wlan network or by using your mobile internet connection. You can set these options in the enviroCar app settings.</li><br><img src='assets/img/support_app/img4.png' alt='Upload Step 1' width='20%'><li>If you don’t want to upload you data in real time, you can upload your generated tracks by clicking on the “Upload button”. Navigate to “My tracks” and click on the button in the upper right corner. After uploading the tracks, a message will be displayed in your notification bar.<br><img src='assets/img/support_app/img5.png' alt='Upload Step 2' width='20%'></li></ol>
<br><ul><li>How to select your car or create a new one:<br>Once you are on the dashboard, you can easily switch to another car or even create a new one. Click on the small “Edit” button to switch to your garage.<br><img src='assets/img/support_app/img6.png' alt='Upload Step 3' width='20%'><br>Scroll through the existing car list, to see, if your car type already exists:<br><img src='assets/img/support_app/img7.png' alt='Upload Step 4' width='20%'><br>Of course, it’s no problem to create a new car type. After completing all lines, click on “Register Car” to create a new entry in the car list.<br><img src='assets/img/support_app/img8.png' alt='Upload Step 5' width='20%'></li>
<li>How to connect your smartphone with your OBD-II adapter:<br>To connect you smartphone with your OBD-II adapter, switch to the BT settings of your smartphone. Enable Bluetooth and search for the new devices. The adapter should be visible within a few seconds. Click on the device and connect it with your smartphone by typing in the correct passkey. It should look like the following:<br><img src='assets/img/support_app/img9.png' alt='Upload Step 6' width='20%'><br>When you’re done, start the enviroCar app, switch to settings and select your OBD-II adapter.<br><img src='assets/img/support_app/img10.png' alt='Upload Step 7' width='20%'></li>
<li>How to start generating a new track:<br>Open the enviroCar menu and click on “Start”. That’s all. The enviroCar app is now ready to collect your car's data.<br><img src='assets/img/support_app/img11.png' alt='Upload Step 7' width='20%'></li></ul>";

//Support_webseite

$register_signin_logout="How to register, sign in and log out ?";
$how_compare_data="How to compare your data?";
$how_share_data="How to share your data?";
$why_use_cookies="Why does this website use cookies?";
$supported_languages="What are the supported languages?";
$description_register='1- From the start page; press "Register" as seen in the picture.
								<br/>
								2- Fill your information inside the input fields, and then press "Register" to create a new account of the entered information.
								<br/>
								3- If you want to reset the information inside the input fields; press "Reset".';
								
$description_signin="1-From the start page; fill in your user name and password and press “SignIn”.";
$description_logout="1- You can log out from any page; notice the image in the top right corner of each page header.";
$logging_out="Logging Out";
$signing_in="Signing In";
$register="Register";
//
$comparing_steps='You vs. your friend! With enviroCar it’s easy to compare your data and results with these of your friends. To allow the comparison of your data both of you have to accept each other as a “friend”. 
Login at the enviroCar platform, navigate to “Comparison” and pick one of your friends from your list.';
$sharing_options='To share your data, there are different ways.<br/>
1. Download your track as a GeoJSON. You can use programms like Quantum GIS to make some analysis. <br/>
2. Sharing data is one of the core concepts of the enviroCar community. On the enviroCar platform, navigate to “Friends” to have a detailed overview about the ongoing activities: Who created new tracks, new friendships, group actions and more.
';
$how_review="How to review your data?";
$review_data='Once you’ve uploaded your generated tracks, you can have a detailed overview about your data by clicking on “Tracks” . <br/>
There you have:<br/>
1. An overall summary of your tracks (Your statistics)<br/>
2. An listed view of your generated tracks. Ordered by the date and time.';
$track_information='Click on one of these tracks to get more information. There you have different options<br/>
1. At the left: Some statistics about the generated track.<br/>
2. At the right: Click on one of the points within your track to have selective information at a specific position.';
$graph_information='You have even more options to review your data<br/>
We put your data into graphs. Click on “Graphs” to have a nice visualization of your data. To have selective information at a specific time, click on the graph itself and zoom in or out to get a better overview.';
$thematic_information='Click on “Thematic maps” to have a look on your data displayed on a map. There you can choose the aspects you are interested in like speed, CO2 emissions, MAF or fuel consumption.
You can navigate in the map by zooming in or out (mousewheel) or pressing you left mouse button and moving it around.';

















$cookies_text='<strong> What are cookies?</strong>
								<br/>
								Cookies are textfiles that contain certain settings information of the website.
								The website places cookies on your browser software in order to store personal settings for example
								that you stay logged in when you visit the website again during a session.
								<br/>
								<br/>
								<strong>And why cookies?</strong>
								<br/>
								Cookies make a website more user friendly and more functional.
								Cookies help to make your visit on our website more comfortable. Because certain settings of you can be stored temporarily.
								For us the website designer cookies help making the programming work and the data administration easier.
								<br/>
								<br/>
								<strong>Should I disable cookies?</strong>
								<br/>
								The using of cookies is combined with functionality on our website. If you disable them
								the use of a few functions could be impossible or they could be used very circuitously.
								<br/>
								<br/>
								<strong>Where can i find more information about cookies?</strong>
								<br/>";
$language_text="1- Until Now; enviroCar supports two languages in our website: English and German language.
2- You can toggle between the languages by pressing the flag symbol as seen in the picture below.';


$created ="Created";
$yourroutes = "Your Routes";
$yourstatistics = "Your Statistics";
$noroutesavailable = "No routes available";

$profile = "Profile";
$dashboard = "My Profile";
$routes = "My Routes";
$friends ="Friends";
$groups = "Groups";
$about = "About";
$community ="Community";
$logout = "Logout";
$comparison ="Comparison";
$informationproduct ="Information Products";
$mapsandstatistics = "Maps & Statistics";
$gettinginvolved = "Getting Involved";
$api = "API";
$data = "Data";
$showapiongithub = "Show API-definition on github.com";

$logoutsuccess = "Successfully logged out";
$currentlynotloggedin = "You are currently not logged in.";
$welcometoex = "Welcome to enviroCar";
$regsuccessfull = "Your registration was successful.";
$logincontinue = "Please login to continue.";
$accountdeleted = "Account deleted.";
$accountdeletedsuccess ="Your Account has been successfully deleted.";

$usernameorpasswordwrong = "Username or Password are wrong, or the user does not exist!";
$registrationunsuccessfull = "Registration not successful.";
$existingusername = "This username or email already exists.";

$graphs ="Graphs";
$thematicmaps = "Thematic maps";

$choosesensor ="Choose sensor";
$routeoverview = "Route overview";

$searchfriends = "Search for Persons";



$envirocar="enviroCar";

$license_ccby = "<a href=\"https://creativecommons.org/licenses/by/3.0/legalcode\" target=\"_blank\">CC-BY</a>";
$license_odbl = "<a href=\"http://opendatacommons.org/licenses/odbl/1.0/\" target=\"_blank\">ODbL</a>";
$license_odbl_summary = "<a href=\"http://opendatacommons.org/licenses/odbl/summary/\" target=\"_blank\">ODbL Summary</a>";

$register_licensereminder = "Remember, all data collected within this project will be anonymised (<a href=\"support.php\" target=\"_blank\">learn how</a>), and made publicly available under ".$license_odbl.".";

$licensing_datalicensing = "Licensing of Data";
$licensing_datalicensingtext = "Data which is available via the ".$envirocar." API is lizensed as ".$license_odbl.". This means: ";
$licensing_allowed = "You are allowed to:";
$licensing_allowedtext ="Copy and redistribute this database, create works from this database, modify copies of this database";
$licensing_aslongas = "As long as you:";
$licensing_aslongastext = "Attribute (mention us as the source of the data), Share copies or modified copies of this database also under ODbL, you keep your database open and accessible.";

$footer_backtotop = "Back to Top";
$footer_imprint = "Imprint";
$footer_terms = "Terms of Use";
$footer_privacy = "Privacy";
$footer_license = "Licensing";

$imprint_imprint = "Imprint";
$imprint_phone = "Phone: ";
$imprint_fax = "Fax: ";
$imprint_email = "E-Mail: ";
$imprint_directors = "Managing Directors: ";
$imprint_registry = "Commercial Registry: ";
$imprint_content = "Content";
$imprint_contenttext = "The ".$envirocar." project team makes every effort to ensure that the material contained in its web site is current, complete and correct. Despite this, errors cannot be completely ruled out. ".$envirocar." does not accept liability for the relevance, accuracy or completeness of the information and material offered in its web site unless the mistake occurred intentionally or through gross negligence. This refers to any loss, additional costs or damage of any kind suffered as a result of any use of any material in this web site. <br/><br>".$envirocar." has no influence on the contents or reliability of the web sites of third party information providers. The following therefore applies to all links: ".$envirocar." has no influence on the design and contents of third party Internet web sites and therefore expressly distances itself from the material of all third party Internet web sites. The declaration is valid for all links given on our web site and the material of all sites reached via banners and links on the ".$envirocar." web site.";

$imprint_copyright = "Copyright";
$imprint_copyrighttext = "The graphics on this website are, licensed as ".$license_ccby.", unless stated otherwise, all texts of this website is licensed as ".$license_ccby.", unless stated otherwise. All data which is accessible with the ".$envirocar." API is licensed under the ".$license_odbl.".";

$member = "Member";
$foundedby = "Founded by";
$leavegroup = "Leave Group";
$joingroup ="Join Group";
$deletegroup ="Delete Group";

$deletedgroup = "Deleted the Group";
$deletegroupsuccess = "Group successfully deleted";
$creategroup = "Create Group";
$searchgroups = "Search Groups";
$groupname = "Group name";
$groupdescription = "Description";

$norecentactivities = "No recent activities";
$joined ="joined a group";
$friended ="made friends with";
$left ="has left the group";
$created ="Created";
$deleted = "Deleted";
$changedProfile = "has changed his profile";
$changedGroup = "has changed a group";
$updated = "Updated";
$createdGroup = "has created a new group";
$createdRoute = "has created a new route";

$userNotExist = "The requested user doesn't exist...";

$activityerror ="Activities couldn't be loaded successfully.";
$creategrouperror ="Group couldn't be created.";
$invalidCharacterError ="Invalid characters in name or description";

$bothFieldsFilled = "Both input fields have to be filled";



$privacy_website_head = "Data collected with this website";
$privacy_website_text_01 = "When using this website, the following data can be collected, and stored for a limited period:"; //todo
$privacy_website_text_02 = "If you register to our services or while you use our services, the following information about you may be collected and stored. The information is deleted when you decide to delete your account.";
$privacy_website_text_03 = "You can delete (with delete we mean delete, there is no way back!) your account and the data associated to it at anytime you feel convenient. Read the FAQ if you want to know how to delete your data and / or your account";
$privacy_website_text_use_datalist = "<li>your ip-address, within our servers access log and error log file</li>";
$privacy_website_text_register_datalist = "<li>The username you have chosen</li><li>The e-mail address you provided</li><li>The password you provided</li><li>The username of persons who added your username as a friend</li><li>The username of the person you added as a friend</li><li>The name of the groups you became a member of</li><li>Your First Name</li><li>Your Family Name</li><li>The country and city you are living in</li><li>Your Website</li><li>Your gender</li><li>Your favored language of the website</li><li>other information which you provided us in a free text form</li>";
$privacy_cookies_head = "Use of cookies";
$privacy_cookies_text_01 = "By using this website you agree to the use of cookies. Those are needed to give you the possibility to login to our services and to select the language of our website. The cookie stores:";
$privacy_cookies_text_02 = "We promise not to use cookies for tracking purposes. Our cookies have a validity of one (1) browser session. This allows you to log out, restart your browser and our website will not recognise you.";
$privacy_cookies_text_use_datalist = "<li>A combination of numbers and characters to identify you</li>";
$privacy_uploadeddata_head = "If you decide to upload data to our service:";
$privacy_uploadeddata_text = "We will collect and store the following data you provided to us:";
$privacy_uploadeddata_datalist = "<li>Location of the measurement</li><li>Speed</li><li>Time and Date</li><li>various parameters of your cars engine</li>";


$personNotFound = "The requested person couldn't be found.";
$routeNotFound = "The requested route couldn't be found.";
$personNotAllowed = "You are not allowed to view the requested profile.";
$routeNotAllowed = "You are not allowed to view the requested route.";
$personError ="Person couldn't be loaded successfully.";
$routeError ="Route couldn't be loaded successfully.";
$groupNotAllowed = "You are not allowed to view the requested group. Join the group to get more information.";
$groupError ="Group couldn't be loaded successfully.";
$friendNotAllowed = "You are not allowed to view the requested friends.";
$friendError ="Friends couldn't be loaded successfully.";
$activityNotAllowed = "You are not allowed to view the requested activities.";
$activityError ="Activities couldn't be loaded successfully.";
$groupNotFound = "The requested group couldn't be found.";
$friendNotFound = "The requested friends couldn't be found.";
$activityNotFound = "The requested activities couldn't be found.";
$statisticsNotFound = "The requested statistics couldn't be loaded successfully.";
$statisticsNotAllowed = "You are not allowed to view the requested statistics.";
$statisticsError ="Statistics couldn't be loaded successfully.";
$mapsNotFound = "The requested maps couldn't be loaded successfully.";
$mapsNotAllowed = "You are not allowed to view the requested maps.";
$mapsError ="Maps couldn't be loaded successfully.";
$groupOfNotFound = "The groups of the requested person couldn't be found.";
$groupOfNotAllowed = "You are not allowed to view the groups of the requested person.";
$groupMemberNotAllowed = "You are not allowed to view the member of the group.";
$groupOfError ="The groups of the requested person couldn't be loaded successfully.";
$joinGroupNotAllowed = "You are not allowed to join this group.";

$allUsers = "All users";

$registrationError = "The server is currently not available. Please try again later.";
$registrationNotAllowed = "Your email address is not registered for our beta-phase. Please contact envirocar@52north.org for a beta-account";
$registrationInvalid = "Your inputs are not valid. Please check the form field and try again.";

$noFriendsYet = "hasn't added you as a friend yet.";
$madeNoFriends ="You haven't made any friends yet. You can search for friends in the search-field in the upper right corner.";

$changeprofile = "Change Profile";
$email = "e-mail";
$firstname = "First name";
$lastname = "Last name";
$birthday = "Birthday";
$gender = "Gender";
$country = "Country";
$location = "Location";
$language = "Language";
$aboutme ="About me";

$fuelType = "Fuel type";
$constructionYear ="Construction Year";
$manufacturer = "Manufacturer";

$addasfriend ="Add as friend";
$removeasfriend ="Delete as friend";

$close = "Close";
$male = "male";
$female ="female";

$deletemyaccount ="Delete account";
$editaccount = "Save changes";

$avatarGravatar ="Your profile picture is based on your email address. You can change it at ";

$pickfriends = "Pick a friend";
$statisticsOf = "Statistics of";
$noDataYet = "did not share any data yet.";
$statistics = "Statistics";


//informationproduct
$interactivemap = "Interactive Maps";
$interactivemap_text = 'Get the <a class="btn btn-primary" href="community_lines.php">interactive map</a> showing the aggregated measurements of the enviroCar routes.<br><br>

		You can also check out our <a class="btn btn-primary" href="community_speed_difference.php">speed-map</a>. We calculated the differences between the maximum speed (based on OpenStreetMap) and the averaged speed (measured via enviroCar), which allows us to analyze, if the traffic flows as planned.<br><br>
		Due to the large amount of measurements the data in the interactive maps are aggregated. We therefore use an <i>Inverse Distance Weighting</i>-Algorithm which combines measurements within a distance of 20m of a road segment (based on OpenStreetMap).
		<i>(Therefore, it can take a while until your uploaded route has been integrated into the map.)</i>';

		
$data_analysis="Data Analysis";
$informationproduct_info = "The following pictures show examplary representations based on the enviroCar data. The maps don't show the current measurements!";
$points_overview="Overview measurement points";
$points_detail="Detail of a measurement point";
$analysis_info='The collected data through the mobile application allow further analysis for example with a GIS program.
		To learn more about how to get access to the enviroCar data, visit the <a href="http://envirocar.github.io/" target="_blank">developer documentation</a> and create your own products!<br>
		For making your own analysis here you can download an example data set as shape file format.<br>';
$data_visualization="Data Visualization";
$co2_map="CO2 emission map";
$speed_map="Speed map";
$interpolation_info="The measurement of coordinates and attribute values from the car that is collected through the mobile application like CO2 emission or speed values make further visualizations possible.";
$comparison_visualization="	 In this example the speed or CO2 values along the measurement route are visualized with an interpolation tool that just creates a continuous surface from sampled point values.";
$comparison_info="Comparison of Speed and CO2 visualization";
$detail_info="Visualization of the measurement data is a useful tool for getting an overview or for making comparisons. Here for example you can easily see that high CO2 values are in the same area of the route as high speed values.";
$speed_map_detail="Speed map detail";
$visualization_multitude="Moreover, the analysis of the measurement can visualize details like speed-up and slow-down areas.";
$GE_visualization="Speed visualization in Google Earth";
$multitude_possibilities="You are able to explore the data from your own ride. There are a multitude of possibilities to analyse and visualize.
		Explore the world of your own data!";	 
	 
	 

$phen_header = 'What are the phenomenons all about?'; 
$phen_description ='<p>
<strong>MAF (Mass air flow)</strong><br>
The MAF sensor measures the amount of air that is flowing into the engine in l/s. The air/fuel-ratio in the engine has to remain constant in order to allow a combustion of the air/fuel-mixture. We therefore measure how much air is used to estimate the current fuel consumption.<br>
Further reading: <a href="http://en.wikipedia.org/wiki/Mass_air_flow_sensor" target="_blank">Wikipedia</a>
</p>
<p>
<strong>Speed</strong><br>
The speed of the vehicle<br>
</p>
<p>
<strong>Consumption</strong><br>
Fuel consumption which is caluclated based on the MAF (Mass air flow) value
</p>
<p>
<strong>RPM</strong><br>
Revelations per minute. This value describes the speed of your engine.<br>
Further reading: <a href="http://en.wikipedia.org/wiki/Revolutions_per_minute" target="_blank">Wikipedia</a>
</p>
<p>
<strong>CO2</strong><br>
Carbon Dioxide is a gas which gets emitted as a byproduct of the fuel-combustion. <br>
Further reading: <a href="http://en.wikipedia.org/wiki/Carbon_dioxide" target="_blank">Wikipedia</a>
</p>';	 
	
//mapsandstatistics.php
$noDescription = "No description available.";
$map = "Map";
$details = "Details";
$hotspot_titel = "CO2 Hot Spots Münster";
$hotspot_description = "Hot Spots Analysis of CO2 values gathered by enviroCar users.";
$speed_titel = "Speed tracks";
$speed_description = "enviroCar tracks showing the measured speed.";
$speedcomparison_titel = "Speed comparison";
$speedcomparison_description = "Speed difference between OpenStreetMap max-speed and enviroCar averaged speed.";

//dataaccess.php
$viaAPIHead = "Via the API";
$viaAPIText = 'The enviroCar-dataserver offers a REST-interface for data-queries. You can find more information here: <a href="http://envirocar.github.io/enviroCar-server/api/" target="_blank">enviroCar-server API.</a>';
$viaDownloadHead = "Via Download";
$viaDownloadText = "Keine Beschreibung verfügbar.";

//about.php
$about_aboutHead = "About enviroCar";
$about_aboutText1 = '<strong>enviroCar</strong> allows you to use your car’s sensor data to investigate the impact that your driving style has on environmental factors such as <strong>fuel consumption</strong>, <strong>CO2</strong>, or <strong>noise</strong> emissions. You and your friends can <strong>compare</strong> your driving statistics and you can compete to become the most efficient driver while also reducing your car’s running costs!
<br/>
Share your data with the enviroCar <strong>citizen science</strong> community and collaborate with others to investigate questions as:
<ul>
<li>What are the effective spatial characteristics of fuel consumption in your city?</li>
<li>How can traffic planning be optimized to reduce emissions effectively?</li>
<li>What can we learn from average speed maps?</li>
</ul>
The urban planners of your city, environmental scientists, as well as other citizens are highly interested in building up a database to solve those kind of questions. With enviroCar we can all contribute to a <strong>new environmental information resource</strong>.
Join the community and help to make our world a little smarter, the flow of traffic smoother and less stressful, and economic driving more fun!';
$about_aboutText2 = 'enviroCar is a community based platform for gathering car-borne sensor data and for producing environmental information. You can access the car’s sensors with your <strong>Android smartphone</strong> and a <strong>Bluetooth OBD-II adapter</strong>. The Smartphone provides you with a lot of information about your driving characteristics. By uploading the data to the enviroCar server you’re contributing anonymized data to the open enviroCar citizen science community.
<br/>
The enviroCar website allows you to:
<ul>
<li>access your data</li>
<li>compare your driving characteristics with others</li>
<li>explore maps and statistics</li>
<li>download data for further processing and analysis.</li>
</ul>';
$about_aboutText3 = 'enviroCar uses a common <strong>OBD-II</strong> adapter (see picture above) that you can easily plug into your car to access data generated by the various sensors of your car. The enviroCar app installed on your <strong>Android smartphone</strong> is able to connect automatically to that OBD2 adapter to read out parameters from your car, such as <strong>current fuel consumption</strong>, <strong>speed</strong>, or <strong>revolutions per minute.</strong>';
$about_gettinginvolvedHead = "Getting Involved";
$asACitizenHead = "As a Citizen (Scientist)";
$asACitizenText = 'All you need to join the community is a Bluetooth <strong>OBD-II Adapter</strong> and an <strong>Android Smart Phone</strong>.
<br/><br/>
There are many OBD-II adapters on the market and their prices range from about 18 EUR (23 USD) up to 150 EUR (200 USD). The OBD-II community has a lot of experience with these adapters, and theoretically most of them should work fine (take a look <a href="http://torque-bhp.com/wiki/Bluetooth_Adapters" target="_blank">here</a> for more details). Please be aware that national laws require products to have appropriate certificates (CE, ECE in Europe). Unfortunately most of these adapters are sold without such certificates. 
As for the European regulations: currently the only adapter which is legaly usable while driving is the Drivedec W4 adapter.
Plug in the adapter to the OBD-II socket within your car. Typically you find this socket in the leg room or below the dashboard of your car. If you cannot find it on your own, you can do a web search for your car type and OBD-II. Once the adapter is plugged in, you just need to pair it with your smartphone. 
<br/><br/>
The enviroCar App is tested for Android 2.3 to version 4.2.2. To install the app on your smartphone, you can use the Play Store and search for <a href="https://play.google.com/store/apps/details?id=org.envirocar.app&amp;hl=en" target="_blank">enviroCar</a>.
<br/><br/>
You can use the app to register for enviroCar. Check your settings, register your car type, select the bluetooth device, and start collecting your first tracks while driving your car. Upload your data to the envirocar server and use the website to connect to friends and groups and explore the <a href="./mapsandstatistics.php">maps & statistics</a> to which you are now contributing to.
<br/><br/>
Use enviroCar and its data to discuss mobility and environment related issues with your friends and with researchers and experts from public authorities. Develop ideas how to gain mobility and to reduce negative impacts on the environment. Join the community and become a <strong>citizen scientist</strong>!';
$asAScientistHead = "As a Scientist";
$asAScientistText = 'You are interested in using the enviroCar platform and  its data for research projects?
<br/><br/>
We recommend to start as a citizen scientist and to get familiar with the enviroCar platform, its data and its features.
<br/><br/>
If you’re interested in the data “as is” you can visit the <a href="./dataaccess.php">data access page</a> where you can either use the <strong>download facilities</strong> or the <strong>Web API</strong> to bring the data into your computing environment for further analysis.
<br/><br/>
If you need special parameters, a community of volunteers, a special quality of data, or simply more information about this citizen science approach we might be able to support. We’d be happy to get in contact with you, to complement your expertise with our experience and network, and to go for joint activities.';
$asAPlannerHead = "As a public authority";
$asAPlannerText = 'You are interested in using the enviroCar approach to interact with the citizens of your  region as to develop new concepts and sustainable change in the field of mobility and environment? 
<br/><br/>
You may use the enviroCar platform “as is” for this purpose. Your IT department and  your domain experts will be able to do the job.  However, we’d be happy to provide you with any support needed, such as consultancy, data analysis, software development,  systems integration, service level agreements, organizing public workshops, etc';
$asADeveloperHead = "As a Developer.";
$asADeveloperText = 'You’d like to develop an application and use the enviroCar platform as a public data source? Check out the <a href="http://envirocar.github.io/enviroCar-server/api" target="_blank">enviroCar API</a> and software at the <a href="https://github.com/enviroCar" target="_blank">enviroCar Github repository</a>. You’ll find an easy to use REST interface to the enviroCar server, which provides you with free access to the data. 
<br/><br/>
You’re invited to join the enviroCar developer community. You may subscribe to the enviroCar@52north.org mailing list  as to get the  latest  infos about the development process and upcoming features.';
$about_faqHead = "Frequently Asked Questions";
$faq_q1 = "Which OBD2 adapters are compatible with enviroCar?";
$faq_q2 = "Is my car supported?";
$faq_q3 = "What about privacy issues?";
$faq_q4 = "I’m a developer and I’m very interested in this project. Is there a way to  make further implementations?";
$faq_q5 = "When will enviroCar be published?";

$faq_a1 = 'There are several OBD2 adapters available in different price ranges (see a list <a href="http://torque-bhp.com/wiki/Bluetooth_Adapters" target="_blank">here</a>). You can buy those adapters on eBay, Amazon, or other shops. Currently, enviroCar is tested with the ELM327 protocol, e.g. used by the low-cost <a href="http://www.amazon.de/Tinxi-Bluetooth-Interface-Diagnose-Testger%C3%A4t/dp/B004YG7J2I/ref=sr_1_7?ie=UTF8&amp;qid=1376651235&amp;sr=8-7&amp;keywords=ELM327+obd2" target="_blank">Tinxi OBD2 adapter</a>, as well as the proprietary Drivedeck protocol, used by the Drivedeck W4 adapter. However, please be aware, that we’re not able to guarantee, that all combinations of adapters / car types / smartphones are working well.  Please check the Web for known compatibility problems. 
<br/><br/>
A very important fact about using OBD2 adapters in Germany is that it’s only allowed to use ECE-certified OBD2 adapters. While driving your car, the usage of adapters without such a certificate is prohibited. Currently the Drivedeck W4 adapter is the only one, which is equipped with all certificates required in Germany. Please check out the national regulations as to be sure that the adapter of your choice can be used without restrictions in your country.';
$faq_a2 = 'The presence of an OBD2 interface within today’s cars is mandated by law in the US as well as Europe. Depending on country and vehicle type, OBD2 was introduced at different times.<br/>
In the US:
<ul>
<li>All cars built after 01.01.1996 have it.</li>
</ul> 
In Europe:
<ul>
<li>All cars with gasoline engine built after 01.01.2001 and with EURO-3 norm (or better) have the OBD2 interface.</li>
<li>All diesel vehicles built after 01.01.2003 have it.</li>
<li>For trucks, the OBD2 support started on 01.01.2005.</li>
</ul>
';
$faq_a3 = 'The data which is uploaded to the enviroCar server is anonymized. I.e., the data do not contain a direct reference to the car or the contributor.  Consequently, data downloaded from the enviroCar server do not contain any references to you.
<br/><br/>
Furthermore, the app allows you to opt for cutting off the first and the last minutes of the tracks as to obfuscate the start and destination of your tracks. This function prevents linking tracks to specific home or business addresses.
<br/><br/>
Of course, the communication between website/app and envirocar server is encrypted and only the authorized database administrator is able to connect uploaded sensor data to a certain user. Only the users themselves are authorized to access their profile data (only the user name and the email address are mandatory).
<br/><br/>
We are sure these measures are an appropriate answer to your privacy concerns.  However, there is no means to achieve a 100% level of security.';
$faq_a4 = 'enviroCar is a community, which is open to everyone. You can download/upload data and use it for your own purpose of statistical analysis. enviroCar offers a <a href="http://envirocar.github.io/enviroCar-server/api" target="_blank">Web API</a>, specifically designed for this purpose.<br/>
The data is publicly available as JSON and as Linked Data, which makes it possible to include enviroCar’s data in any services.<br/>
You are welcome to get in contact with us discussing your suggestions, thoughts and ideas. enviroCar is fully open source and all components are available on <a href="https://github.com/enviroCar" target="_blank">our Github repository</a>. We’d be happy to see you as a contributor!';
$faq_a5 = "Currently the project is open to beta testers, i.e. people who are ready to accept, that we’re still in a development phase, where we have to change the software continuously as to get it ready for public use.  We are happy about critical feedback of beta testers in this phase. Our goal is to create a cool, usable, and fun platform up and running. We expect to get a stable release of all components available to the public by the end of this year (2013).";

//route.php

$route_distance = "DISTANCE";
$route_fuelConsumption = "FUEL CONSUMPTION";
$route_CO2 = "CO2 EMISSION";
$route_idleTime = "IDLE TIME";
$route_avgSpeed = "AVERAGE SPEED";
$route_minutes = "m";
$route_fuelGas = "gasoline";
$route_fuelDiesel = "diesel";
$route_dropup_fuelConsumption = "consumption";
$route_dropup_speed = "speed";
$route_requestFuelPrice = "Requesting current fuel prices...";
$route_drivenRoute = "driven route";
$route_baseLayer = "base layer";
?>
