<?php 
// index.php
$index_invalid_login_name="Invalid Login Name"; 
$index_empty_password="Password cannot be empty"; 
$index_access_denied="Access denied!";
$index_Please_sign_in="Please sign in";
$index_password="Password";
$index_user_details="User details";
$index_register="Register";
$index_get_App="Get our App soon!";
$index_get_it_on_google="Get it on Google Play!";
$index_be_a_citizen_scientist="Be a Citizen Scientist";
$index_help_the_world="Help the world become a better place by sharing your data with scientists from all over the world! Or use existing data for your own research!";
$index_support_indiegogo="Support us on Indiegogo";
$index_this_is_community="This is a community, it's an app and it's a website.<br> enviroCar is our contribution to a smarter world.<br> We will generate knowledge about car traffic and its emissions on our streets and we will raise awareness of environmental consequences of our driving behaviour.";
$index_how_it_works="How does it work?";
$index_three_steps_to="Three steps to become a citizen scientist";
$index_register="Register";
$index_sign_in="Sign in";
$index_user_name="User name";
$index_make_smarter="Make our cities smarter!";
$index_empty_password="sorry, but you can't have an empty password.";
$index_name_missing="everybody should have a name, even you.";
$index_credentials_invalid="nice try, but empty credentials are invalid.";
$index_having_account="Are you sure, of having an account?";
$index_create_new_one="You can create a new one. It's free";
$index_wrong_name="Wait, that's not my name!";
$index_continue_dashboard="Continue to your dashboard";
$index_welcome="Welcome";

// registration.php
$reg_registration="Registration";
$reg_username="User name";
$reg_email="Email Adress";
$reg_password="Password";
$reg_repeat_password="Repeat Password";
$reg_btn_register="Register";
$reg_btn_reset="Reset";
$invalid_input ="Invalid input. Please check the hints and try again.";


// dashboard.php
$dashboard_recent_avtivities="Recent Activities";
$dashboard_view_details="View details";
$dashboard_overview="Overview";
$dashboard_friend_activities="Friend Activities";
$dashboard_group_activities="Group Activities";

//function registration
$freg_invalidemail="Invalid Email";
$freg_empty_nickname="Nickname cannot be empty";
$freg_empty_password="Password cannot be empty";
$freg_notidentic_password='Passwords are not identic';


// Support
$main_information="Main information";
$mobile_app="Mobile application";
$website="Website";
$what_enviro="What is EnviroCar?";
$how_enviro="How does EnviroCar works?";
$enviro_description="A community based system for gathering your car’s data with your smartphone bluetooth-paired OBD2 adapter to 
								make your city smarter.	<br/>enviroCar allows you to drive more efficiently by giving you for example full 
								insight in consumption and costs. It allows you to compare your driving statistics with friends and to enjoy 
								competing to become the most efficient driver. Furthermore, enviroCar enables you to contribute data collected 
								by your car to the open enviroCar community. <br/><br/>From those data,	enviroCar generates information about 
								traffic in your city and its emissions on our streets. The information will support e.g. urban planners to improve
								traffic light phases or to clarify the impact of traffic calming measures. <br/>enviroCar is the first platform to 
								collect information about the actual emissions right when they happen because it is connected directly to the sensors in the car.
								Join the community and help to make our world a little bit smarter, traffic less stressful, and economic driving more fun!";
$back_top="Back to top";
$enviro_description_detail="enviroCar uses an OBD2 adapter that you can easily plug into your car to access data generated by the 
								various sensors of your car. The enviroCar App installed on your smartphone is able to connect automatically
								to that OBD2 adapter to read out parameters from your car, such as current fuel consumption or revolutions 
								per minute. This way, enviroCar can accurately measure your driving costs, can compute emitted CO2 or even 
								estimate the noise created by your car.";
$enviro_description_detail2="By using OBD2 adapter, enviroCar is able to receive your cars data by pairing your smartphone via Bluetooth with the adapter. The smartphone app analyzes and parses the data to give you in the app and on the enviroCar these information, which you want to see.";

//Support_mobile_application
$how_register="How to register from your mobile phone?";
$how_download="How to download enviroCar application?";
$how_synchronize="How to synchronize your data?";
$registration="Registration";
$registration_steps="Registration steps";
$downloading="Downloading";
$download_steps="Downloading steps";
$synchronization="Synchronization";
$synchronization_steps="Synchronization steps";

//Support_webseite

$register_signin_logout="How to register, sign in and log out ?";
$how_compare_data="How to compare your data?";
$how_share_data="How to share your data?";
$why_use_cookies="Why does this website use cookies?";
$supported_languages="What are the supported languages?";
$description_register='1- From the start page; press "Register" as seen in the picture.
								<br/>
								2- Fill your information inside the input fields, and then press "Register" to create a new account of the entered information.
								<br/>
								3- If you want to reset the information inside the input fields; press "Reset".';
								
$description_signin="1-From the start page; fill in your user name and password and press “SignIn”.";
$description_logout="1- You can log out from any page; notice the image in the top right corner of each page header.";
$logging_out="Logging Out";
$signing_in="Signing In";
$register="Register";
$comparing_steps="comparing steps and options";
$sharing_options="sharing options";
$cookies_text='<strong> What are cookies?</strong>
								<br/>
								Cookies are textfiles that contain certain settings information of the website.
								The website places cookies on your browser software in order to store personal settings for example
								that you stay logged in when you visit the website again during a session.
								<br/>
								<br/>
								<strong>And why cookies?</strong>
								<br/>
								Cookies make a website more user friendly and more functional.
								Cookies help to make your visit on our website more comfortable. Because certain settings of you can be stored temporarily.
								For us the website designer cookies help making the programming work and the data administration easier.
								<br/>
								<br/>
								<strong>Should I disable cookies?</strong>
								<br/>
								The using of cookies is combined with functionality on our website. If you disable them
								the use of a few functions could be impossible or they could be used very circuitously.
								<br/>
								<br/>
								<strong>Where can i find more information about cookies?</strong>
								<br/>";
$language_text="1- Until Now; enviroCar supports two languages in our website: English and German language.
2- You can toggle between the languages by pressing the flag symbol as seen in the picture below.';


$created ="Created";
$yourroutes = "Your Routes";
$yourstatistics = "Your Statistics";
$noroutesavailable = "No routes available";

$profile = "Profil";
$activities = "Dashboard";
$routes = "Routes";
$friends ="Friends";
$groups = "Groups";
$help = "Help";
$community ="Community";
$logout = "Logout";
$comparison ="Comparison";
$informationproduct ="Information Products";
$api = "API";
$showapiongithub = "Show API-definition on github.com";

$logoutsuccess = "Successfully logged out";
$currentlynotloggedin = "You are currently not logged in.";
$welcometoex = "Welcome to enviroCar";
$regsuccessfull = "Your registration was successful.";
$logincontinue = "Please login to continue.";
$accountdeleted = "Account deleted.";
$accountdeletedsuccess ="Your Account has been successfully deleted.";

$usernameorpasswordwrong = "Username or Password are wrong, or the user does not exist!";
$registrationunsuccessfull = "Registration not successful.";
$existingusername = "This username or email already exists.";

$graphs ="Graphs";
$thematicmaps = "Thematic maps";

$choosesensor ="Choose sensor";
$routeoverview = "Route overview";

$searchfriends = "Search for Persons";



$envirocar="enviroCar";

$license_ccby = "<a href=\"https://creativecommons.org/licenses/by/3.0/legalcode\" target=\"_blank\">CC-BY</a>";
$license_odbl = "<a href=\"http://opendatacommons.org/licenses/odbl/1.0/\" target=\"_blank\">ODbL</a>";
$license_odbl_summary = "<a href=\"http://opendatacommons.org/licenses/odbl/summary/\" target=\"_blank\">ODbL Summary</a>";

$register_licensereminder = "Remember, all data collected within this project will be anonymised (<a href=\"support.php\" target=\"_blank\">learn how</a>), and made publicly available under ".$license_odbl.".";

$licensing_datalicensing = "Licensing of Data";
$licensing_datalicensingtext = "Data which is available via the ".$envirocar." API is lizensed as ".$license_odbl.". This means: ";
$licensing_allowed = "You are allowed to:";
$licensing_allowedtext ="Copy and redistribute this database, create works from this database, modify copies of this database";
$licensing_aslongas = "As long as you:";
$licensing_aslongastext = "Attribute (mention us as the source of the data), Share copies or modified copies of this database also under ODbL, you keep your database open and accessible.";

$footer_backtotop = "Back to Top";
$footer_imprint = "Imprint";
$footer_terms = "Terms of Use";
$footer_privacy = "Privacy";
$footer_license = "Licensing";

$imprint_imprint = "Imprint";
$imprint_phone = "Phone: ";
$imprint_fax = "Fax: ";
$imprint_email = "E-Mail: ";
$imprint_directors = "Managing Directors: ";
$imprint_registry = "Commercial Registry: ";
$imprint_content = "Content";
$imprint_contenttext = "The ".$envirocar." project team makes every effort to ensure that the material contained in its web site is current, complete and correct. Despite this, errors cannot be completely ruled out. ".$envirocar." does not accept liability for the relevance, accuracy or completeness of the information and material offered in its web site unless the mistake occurred intentionally or through gross negligence. This refers to any loss, additional costs or damage of any kind suffered as a result of any use of any material in this web site. <br/><br>".$envirocar." has no influence on the contents or reliability of the web sites of third party information providers. The following therefore applies to all links: ".$envirocar." has no influence on the design and contents of third party Internet web sites and therefore expressly distances itself from the material of all third party Internet web sites. The declaration is valid for all links given on our web site and the material of all sites reached via banners and links on the ".$envirocar." web site.";

$imprint_copyright = "Copyright";
$imprint_copyrighttext = "The graphics on this website are, licensed as ".$license_ccby.", unless stated otherwise, all texts of this website is licensed as ".$license_ccby.", unless stated otherwise. All data which is accessible with the ".$envirocar." API is licensed under the ".$license_odbl.".";

$member = "Member";
$foundedby = "Founded by";
$leavegroup = "Leave Group";
$joingroup ="Join Group";
$deletegroup ="Delete Group";

$deletedgroup = "Deleted the Group";
$deletegroupsuccess = "Group successfully deleted";
$creategroup = "Create Group";
$searchgroups = "Search Groups";
$groupname = "Group name";
$groupdescription = "Description";

$norecentactivities = "No recent activities";
$joined ="joined a group";
$friended ="made friends with";
$left ="has left the group";
$created ="Created";
$deleted = "Deleted";
$changedProfile = "has changed his profile";
$changedGroup = "has changed a group";
$updated = "Updated";
$createdGroup = "has created a new group";
$createdRoute = "has created a new route";

$userNotExist = "The requested user doesn't exist...";

$activityerror ="Activities couldn't be loaded successfully.";
$creategrouperror ="Group couln\'t be created.";
$invalidCharacterError ="Invalid characters in name or description";

$bothFieldsFilled = "Both input fiels have to be filled";



$privacy_website_head = "Data collected with this website";
$privacy_website_text_01 = "When using this website, the following data can be collected, and stored for a limited period:"; //todo
$privacy_website_text_02 = "If you register to our services or while you use our services, the following information about you may be collected and stored. The information is deleted when you decide to delete your account.";
$privacy_website_text_03 = "You can delete (with delete we mean delete, there is no way back!) your account and the data associated to it at anytime you feel convenient. Read the FAQ if you want to know how to delete your data and / or your account";
$privacy_website_text_use_datalist = "<li>your ip-address, within our servers access log and error log file</li>";
$privacy_website_text_register_datalist = "<li>The username you have chosen</li><li>The e-mail address you provided</li><li>The password you provided</li><li>The username of persons who added your username as a friend</li><li>The username of the person you added as a friend</li><li>The name of the groups you became a member of</li><li>Your First Name</li><li>Your Family Name</li><li>The country and city you are living in</li><li>Your Website</li><li>Your gender</li><li>Your favored language of the website</li><li>other information which you provided us in a free text form</li>";
$privacy_cookies_head = "Use of cookies";
$privacy_cookies_text_01 = "By using this website you agree to the use of cookies. Those are needed to give you the possibility to login to our services and to select the language of our website. The cookie stores:";
$privacy_cookies_text_02 = "We promise not to use cookies for tracking purposes. Our cookies have a validity of one (1) browser session. This allows you to log out, restart your browser and our website will not recognise you.";
$privacy_cookies_text_use_datalist = "<li>A combination of numbers and characters to identify you</li>";
$privacy_uploadeddata_head = "If you decide to upload data to our service:";
$privacy_uploadeddata_text = "We will collect and store the following data you provided to us:";
$privacy_uploadeddata_datalist = "<li>Location of the measurement</li><li>Speed</li><li>Time and Date</li><li>various parameters of your cars engine</li>";


$personNotFound = "The requested person could't be found.";
$routeNotFound = "The requested route couldn't be found.";
$personNotAllowed = "You are not allowed to view the requested profile.";
$routeNotAllowed = "You are not allowed to view the requested route.";
$personError ="Person couldn't be loaded successfully.";
$routeError ="Route couldn't be loaded successfully.";
$groupNotAllowed = "You are not allowed to view the requested group. Join the group to get more information.";
$groupError ="Group couldn't be loaded successfully.";
$friendNotAllowed = "You are not allowed to view the requested friends.";
$friendError ="Friends couldn't be loaded successfully.";
$activityNotAllowed = "You are not allowed to view the requested activities.";
$activityError ="Activities couldn't be loaded successfully.";
$groupNotFound = "The requested group couldn't be found.";
$friendNotFound = "The requested friends couldn't be found.";
$activityNotFound = "The requested activities couldn't be found.";
$statisticsNotFound = "The requested statistics couldn't be loadel successfully.";
$statisticsNotAllowed = "You are not allowed to view the requested statistics.";
$statisticsError ="Statistics couldn't be loaded successfully.";
$groupOfNotFound = "The groups of the requested person couldn't be found.";
$groupOfNotAllowed = "You are not allowed to view the groups of the requested person.";
$groupMemberNotAllowed = "You are not allowed to view the member of the group.";
$groupOfError ="The groups of the requested person couldn't be loaded successfully.";
$joinGroupNotAllowed = "You are not allowed to join this group.";

$noFriendsYet = "hasn't added you as a friend yet.";


$firstname = "First name";
$lastname = "Last name";
$birthday = "Birthday";
$gender = "Gender";
$country = "Country";
$location = "Location";
$language = "Language";
$aboutme ="About me";

$fuelType = "Fuel type";
$constructionYear ="Construction Year";
$manufacturer = "Manufacturer";

$addasfriend ="Add as friend";
$removeasfriend ="Delete as friend";

$close = "Close";
$male = "male";
$female ="female";

$deletemyaccount ="Delete account";
$editaccount = "Edit";

$avatarGravatar ="Your profile picture is based on your email adress. You can change it at ";

$pickfriends = "Pick a friend";
$statisticsOf = "Statistics of";
$noDataYet = "did not share any data yet.";
$statistics = "Statistics";


//informationproduct
$interactivemap = "Interactive Maps";
$interactivemap_text = 'Get the <a href="community_lines.php">interactive map</a> showing the aggregated measurements of the enviroCar routes and see where ou contributed to the information products! <br><br>

		You can also check out our <a href="community_speed_difference.php">speed-map</a>. We calculated the differences between the maximum speed (based on OpenStreetMap) and the averaged speed (measured via enviroCar), which allows us to analyze, if the traffic flows as planned.<br>
		<i>(It may can take a while until your uploaded route has been integrated into the map.)</i>';

		
$data_analysis="Data Analysis";
$points_overview="Overview measurement points";
$points_detail="Detail of a measurement point";
$analysis_info='The collected data through the mobile application allow further analysis for example with a GIS program.
		To learn more about how to get access to the enviroCar data, visit the <a href="">developer documentation</a> and create your own products!<br>
		For making your own analysis here you can download an example data set as shape file format.<br>';
$data_visualization="Data Visualization";
$co2_map="CO2 emission map";
$speed_map="Speed map";
$interpolation_info="The measurement of coordinates and attribute values from the car that is collected through the mobile application like CO2 emission or speed values make further visualizations possible.";
$comparison_visualization="	 In this example the speed or CO2 values along the measurement route are visualized with an interpolation tool that just creates a continuous surface from sampled point values.";
$comparison_info="Comparison of Speed and CO2 visualization";
$detail_info="Visualization of the measurement data is a useful tool for getting an overview or for making comparisons. Here for example you can easily see that high CO2 values are in the same area of the route as high speed values.";
$speed_map_detail="Speed map detail";
$visualization_multitude="Moreover, the analysis of the measurement can visualize details like speed-up and slow-down areas.";
$GE_visualization="Speed visualization in Google Earth";
$multitude_possibilities="You are able to explore the data from your own ride. There are a multitude of possibilities to analyse and visualize.
		Explore the world of your own data!";	 
	 
$faq_q1 = "How does it work?";
$faq_q2 = "How to get started? What are the requirements?";
$faq_q3 = "Which OBD2 adapters are compatible with enviroCar?";
$faq_q4 = "Is my car supported?";
$faq_q5 = "Why do we need Indiegogo backers?";
$faq_q6 = "What about privacy and security?";
$faq_q7 = "I’m a developer and very interested in this project. Is it possible to make further implementations?";
$faq_q8 = "What’s next?";
$faq_q9 = "When will enviroCar be published?";
$faq_q10 = "Can we ship to your country?";

$faq_a1 = "By using an OBD2 adapter, enviroCar is able to receive your car's data by connecting your smartphone with the adapter via Bluetooth. The smartphone app sends the data to the server, which analyzes and processes the data. You can look at the data in the app and on the website.";
$faq_a2 = "Plug your OBD2 adapter into the OnBoard Diagnostic (OBD) port of your car. Download and install the app, connect it with your adapter and you’re ready to be a part of enviroCar.";
$faq_a3 = "There are quite a lot OBD2 adapters for using enviroCar in different price ranges. You can buy these adapters on eBay, Amazon or other shops. Please keep in mind that there are many which won’t work for enviroCar, so you should take a look at some reviews. A very important fact about using OBD2 adapters in Germany: It’s only allowed to use CE-certified OBD2 adpaters. While driving your car, the usage of adapters without a CE-certificate is prohibited. If you want to be sure to have the right adapter, contact us or make a pledge for the 199€ pledge (enviroCar device (early bird)) on Indiegogo, which includes the right adapter.";
$faq_a4 = "The use of OBD2 interfaces was introduced at different times, depending on country and vehicle type.	In the USA all cars built on 01.01.1996 or later have it. In Europe, all new cars with an Otto-motor (using benzine) from 01.01.2001 and with the EURO-3 Norm have the OBD2 interface. For diesel vehicles it was supported beginning on 01.01.2003. For trucks the OBD2 support started on 01.01.2005";
$faq_a5 = "With the help of Indiegogo we want to collect 10.000€ for our future work. With your donation, you can support the future of the enviroCar project. We want to offer the possibility to review your and other data for a long time, and to make your city smarter. Help us, that students and other people can extend and work on this project.";
$faq_a6 = "Of course we are aware of privacy issues. All your data will be anonymized, so nobody will be able to collect sensitive, specific or person-related data about your usage. Your security is a very important topic for us and you won't have to worry about it by using enviroCar.";
$faq_a7 = "The project is open source software, so everybody can participate. Please contact us, any support is welcome.";
$faq_a8 = "For our goal to make your place a little bit smarter, you’re the most important person. The next steps include further implementation of new features, as well as building up the enviroCar community.";
$faq_a9 = "We are working hard on the enviroCar system. For now we have implemented first prototypes for app and website. Further work will be on adding more features and implementing useful functions for you. We plan to release enviroCar soon. Please be patient and look for our updates.";
$faq_a10 = "We will ship to all countries";	 
	 
	 
	 
?>
